// Generated by https://quicktype.io

export interface Hotels {
  hotel_name:  string;
  street:      string;
  city:        string;
  postal_code: string;
  price:       number;
  email:       string;
}
